# Generated by Django 3.2.6 on 2021-08-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsersContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone_number', models.IntegerField(default=0)),
                ('allusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.allusers')),
            ],
        ),
    ]
